/* Trigger maintain, bảng lịch sử tiền bạc, view báo cáo. B3-3: tách khỏi schema.ts. */
import type { Db } from './pg-compat';

/* -------------------------------------------------------------------------------------
 * Trigger maintain: MỖI BẢNG CHỈ CÓ ĐÚNG 1 TRIGGER (BEFORE UPDATE, sửa trực tiếp NEW).
 * PL/pgSQL cho phép gán NEW.column trong BEFORE trigger — sạch và an toàn hơn
 * hẳn cách inner-UPDATE của SQLite (không bao giờ có chuyện trigger kích chéo).
 * ----------------------------------------------------------------------------------- */
export const MAINTAIN_TABLES = [
  'users',
  'centers',
  'teachers',
  'students',
  'rooms',
  'classes',
  'enrollments',
  'sessions',
  'attendance',
  'teacher_checkins',
  'credits',
  'parents',
  'leave_requests',
  'grades',
  'reviews',
  'referrals',
  'rubrics',
  'rubric_criteria',
  'homework',
  'homework_attachments',
  'homework_completions',
  'homework_submissions',
  'quiz_questions',
  'quiz_options',
  'quiz_attempts',
  'question_bank',
  'question_bank_options',
  'trial_registrations',
  'leads',
  'reminders',
  // Các bảng có updated_at nhưng trước đây thiếu trigger maintain
  'roles',
  'salary_rules',
  'payment_txns',
  'parent_students',
  'homework_targets',
  'homework_scores',
] as const;

/** Bảng có optimistic locking (cột version). */
const VERSIONED_TABLES = ['invoices', 'payments', 'students', 'classes', 'homework'] as const;

const TS_EXPR = `to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')`;

export async function createTriggers(db: Db): Promise<void> {
  await db.exec(`
CREATE OR REPLACE FUNCTION maintain_row() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
    NEW.updated_at := ${TS_EXPR};
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION maintain_row_versioned() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
    NEW.updated_at := ${TS_EXPR};
  END IF;
  IF NEW.version IS NULL OR NEW.version = OLD.version THEN
    NEW.version := OLD.version + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
`);
  // payments/invoices do createHistoryTables() đảm nhiệm (trigger audit gộp maintain)
  // DATA-11: KHÔNG DROP + CREATE mỗi lần boot (ACCESS EXCLUSIVE trên bảng nóng) —
  // chỉ tạo trigger còn thiếu. Thân hàm cập nhật qua CREATE OR REPLACE FUNCTION ở trên.
  const existing = await existingTriggers(db);
  for (const t of MAINTAIN_TABLES) {
    if (existing.has(`trg_${t}_maintain`)) continue;
    const versioned = (VERSIONED_TABLES as readonly string[]).includes(t);
    const fn = versioned ? 'maintain_row_versioned()' : 'maintain_row()';
    await db.exec(
      `CREATE TRIGGER trg_${t}_maintain BEFORE UPDATE ON ${t} FOR EACH ROW EXECUTE FUNCTION ${fn};`
    );
  }
}

/** Tên các trigger (không nội bộ) đang có trong DB. */
async function existingTriggers(db: Db): Promise<Set<string>> {
  const r = await db.query('SELECT tgname FROM pg_trigger WHERE NOT tgisinternal');
  return new Set((r.rows as { tgname: string }[]).map((x) => x.tgname));
}

/* -------------------------------------------------------------------------------------
 * Lịch sử BẤT BIẾN của tiền bạc (immutable financial trail).
 * Như bản SQLite: mọi INSERT/UPDATE/DELETE trên payments/invoices đều được ghi
 * snapshot JSON. BEFORE trigger nên vừa ghi history vừa bảo trì
 * updated_at/version trong cùng một lần — không cần trigger riêng.
 * ----------------------------------------------------------------------------------- */
export async function createHistoryTables(db: Db): Promise<void> {
  await db.exec(`
CREATE TABLE IF NOT EXISTS payment_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id INTEGER NOT NULL,
  action TEXT NOT NULL CONSTRAINT chk_ph_action CHECK (action IN ('insert', 'update', 'delete')),
  old_data TEXT,
  new_data TEXT,
  changed_by INTEGER,
  changed_at TEXT NOT NULL DEFAULT (${TS_EXPR})
);
CREATE TABLE IF NOT EXISTS invoice_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  action TEXT NOT NULL CONSTRAINT chk_ih_action CHECK (action IN ('insert', 'update', 'delete')),
  old_data TEXT,
  new_data TEXT,
  changed_by INTEGER,
  changed_at TEXT NOT NULL DEFAULT (${TS_EXPR})
);
-- DATA-18: lưu cả vai trò actor — users.id và parents.id là 2 sequence riêng nên
-- changed_by = 5 có thể là staff #5 hoặc phụ huynh #5.
ALTER TABLE payment_history ADD COLUMN IF NOT EXISTS changed_by_role TEXT;
ALTER TABLE invoice_history ADD COLUMN IF NOT EXISTS changed_by_role TEXT;
CREATE INDEX IF NOT EXISTS idx_payment_history_payment ON payment_history(payment_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_history_invoice ON invoice_history(invoice_id, changed_at DESC);
CREATE TABLE IF NOT EXISTS idempotency_keys (
  user_key TEXT NOT NULL,
  key TEXT NOT NULL,
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  body_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing'
    CONSTRAINT chk_idempotency_status CHECK (status IN ('processing', 'done')),
  status_code INTEGER,
  response_body TEXT,
  created_at TEXT NOT NULL DEFAULT (${TS_EXPR}),
  CONSTRAINT pk_idempotency_keys PRIMARY KEY (user_key, key)
);
CREATE INDEX IF NOT EXISTS idx_idempotency_created ON idempotency_keys(created_at);

/* Index cho các FK nóng — PostgreSQL không tự index FK, thiếu sẽ Seq Scan khi JOIN/filter.
 * Chọn lọc theo tần suất query thực tế (audit performance 2026-10-09), không index bừa.
 * v23 (PERF-3): bỏ index trùng/tiền tố của index composite hoặc UNIQUE (danh sách: migration v23). */
CREATE INDEX IF NOT EXISTS idx_invoices_center ON invoices(center_id);
CREATE INDEX IF NOT EXISTS idx_classes_center ON classes(center_id);
CREATE INDEX IF NOT EXISTS idx_teachers_center ON teachers(center_id);
CREATE INDEX IF NOT EXISTS idx_grades_student ON grades(student_id);
-- Index cho quiz hot path (chống N+1)
CREATE INDEX IF NOT EXISTS idx_quiz_options_question ON quiz_options(question_id);
CREATE INDEX IF NOT EXISTS idx_quiz_answers_attempt ON quiz_answers(attempt_id);
CREATE INDEX IF NOT EXISTS idx_sessions_date ON sessions(date);
CREATE INDEX IF NOT EXISTS idx_attendance_session ON attendance(session_id);
CREATE INDEX IF NOT EXISTS idx_teacher_checkins_lookup ON teacher_checkins(teacher_id, session_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_center ON audit_logs(center_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity, entity_id);
CREATE INDEX IF NOT EXISTS idx_parent_students_parent ON parent_students(parent_id);
CREATE INDEX IF NOT EXISTS idx_parent_students_student ON parent_students(student_id);

CREATE OR REPLACE FUNCTION audit_payment() RETURNS TRIGGER AS $$
DECLARE
  -- Actor của request ('<userId>:<role>') do middleware auth gắn qua
  -- SET LOCAL app.user_id. missing_ok=true -> NULL khi chạy ngoài request
  -- (seed, scheduler, migration); ép kiểu an toàn, rác -> NULL chứ không lỗi.
  v_changed_by INTEGER;
  v_role TEXT := NULLIF(split_part(COALESCE(current_setting('app.user_id', true), ''), ':', 2), '');
BEGIN
  BEGIN
    v_changed_by := NULLIF(split_part(current_setting('app.user_id', true), ':', 1), '')::INTEGER;
  EXCEPTION WHEN invalid_text_representation THEN
    v_changed_by := NULL;
  END;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO payment_history (payment_id, action, new_data, changed_by, changed_by_role)
    VALUES (NEW.id, 'insert',
      json_build_object('id', NEW.id, 'invoice_id', NEW.invoice_id, 'amount', NEW.amount,
                        'status', NEW.status, 'method', NEW.method, 'paid_at', NEW.paid_at),
      v_changed_by, v_role);
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO payment_history (payment_id, action, old_data, new_data, changed_by, changed_by_role)
    VALUES (NEW.id, 'update',
      json_build_object('id', OLD.id, 'invoice_id', OLD.invoice_id, 'amount', OLD.amount,
                        'status', OLD.status, 'method', OLD.method, 'paid_at', OLD.paid_at),
      json_build_object('id', NEW.id, 'invoice_id', NEW.invoice_id, 'amount', NEW.amount,
                        'status', NEW.status, 'method', NEW.method, 'paid_at', NEW.paid_at),
      v_changed_by, v_role);
    IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
      NEW.updated_at := ${TS_EXPR};
    END IF;
    IF NEW.version IS NULL OR NEW.version = OLD.version THEN
      NEW.version := OLD.version + 1;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO payment_history (payment_id, action, old_data, changed_by, changed_by_role)
    VALUES (OLD.id, 'delete',
      json_build_object('id', OLD.id, 'invoice_id', OLD.invoice_id, 'amount', OLD.amount,
                        'status', OLD.status, 'method', OLD.method, 'paid_at', OLD.paid_at),
      v_changed_by, v_role);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION audit_invoice() RETURNS TRIGGER AS $$
DECLARE
  v_changed_by INTEGER;
  v_role TEXT := NULLIF(split_part(COALESCE(current_setting('app.user_id', true), ''), ':', 2), '');
BEGIN
  BEGIN
    v_changed_by := NULLIF(split_part(current_setting('app.user_id', true), ':', 1), '')::INTEGER;
  EXCEPTION WHEN invalid_text_representation THEN
    v_changed_by := NULL;
  END;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO invoice_history (invoice_id, action, new_data, changed_by, changed_by_role)
    VALUES (NEW.id, 'insert',
      json_build_object('id', NEW.id, 'student_id', NEW.student_id, 'amount', NEW.amount,
                        'status', NEW.status, 'due_date', NEW.due_date),
      v_changed_by, v_role);
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO invoice_history (invoice_id, action, old_data, new_data, changed_by, changed_by_role)
    VALUES (NEW.id, 'update',
      json_build_object('id', OLD.id, 'student_id', OLD.student_id, 'amount', OLD.amount,
                        'status', OLD.status, 'due_date', OLD.due_date),
      json_build_object('id', NEW.id, 'student_id', NEW.student_id, 'amount', NEW.amount,
                        'status', NEW.status, 'due_date', NEW.due_date),
      v_changed_by, v_role);
    IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
      NEW.updated_at := ${TS_EXPR};
    END IF;
    IF NEW.version IS NULL OR NEW.version = OLD.version THEN
      NEW.version := OLD.version + 1;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO invoice_history (invoice_id, action, old_data, changed_by, changed_by_role)
    VALUES (OLD.id, 'delete',
      json_build_object('id', OLD.id, 'student_id', OLD.student_id, 'amount', OLD.amount,
                        'status', OLD.status, 'due_date', OLD.due_date),
      v_changed_by, v_role);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

`);
  const existing = await existingTriggers(db);
  for (const t of ['payment', 'invoice']) {
    if (existing.has(`trg_${t}s_audit`)) continue;
    await db.exec(
      `CREATE TRIGGER trg_${t}s_audit BEFORE INSERT OR UPDATE OR DELETE ON ${t}s FOR EACH ROW EXECUTE FUNCTION audit_${t}();`
    );
  }
}

/* -------------------------------------------------------------------------------------
 * View báo cáo chỉ đọc.
 * ----------------------------------------------------------------------------------- */
export async function createViews(db: Db): Promise<void> {
  await db.exec(`
CREATE OR REPLACE VIEW v_invoice_balance AS
SELECT
  i.id AS invoice_id,
  i.center_id,
  i.student_id,
  i.class_id,
  i.amount AS invoice_amount,
  i.status,
  i.due_date,
  COALESCE((
    SELECT SUM(p.amount) FROM payments p
    WHERE p.invoice_id = i.id AND p.status = 'confirmed'
  ), 0) AS paid_confirmed,
  i.amount - COALESCE((
    SELECT SUM(p.amount) FROM payments p
    WHERE p.invoice_id = i.id AND p.status = 'confirmed'
  ), 0) AS balance
FROM invoices i;
`);
}
