/* =====================================================================================
 * EduCenterPro — CANONICAL DATABASE SCHEMA (PostgreSQL, single source of truth)
 * =====================================================================================
 *
 * File này là định nghĩa DUY NHẤT của cấu trúc database. Mọi thay đổi cấu trúc
 * đều bắt đầu từ đây, sau đó mới viết migration trong migrations.ts.
 *
 * QUY ƯỚC (bắt buộc tuân thủ khi thêm bảng/cột mới):
 *
 * 1. Đặt tên: snake_case. Khóa chính `id INTEGER GENERATED BY DEFAULT AS IDENTITY
 *    PRIMARY KEY` (cho phép chèn id tường minh khi cần, vd: seed/test),
 *    trừ bảng nối nhiều-nhiều dùng khóa chính composite.
 *    Cột khóa ngoại đặt tên `<bang>_id` (vd: student_id -> students.id).
 *
 * 2. Thời gian: TEXT theo ISO-8601 'YYYY-MM-DD HH24:MI:SS' (giờ server),
 *    DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')).
 *    Cố tình dùng TEXT thay vì TIMESTAMPTZ để giữ nguyên semantics so sánh chuỗi
 *    và kiểu dữ liệu JS (string) như trước — tránh ripple đổi toàn bộ app.
 *    Mọi bảng nghiệp vụ chính có `created_at`; bảng mutable có thêm
 *    `updated_at` và trigger tự động chạm (BEFORE UPDATE, sửa trực tiếp NEW).
 *
 * 3. Tiền tệ: DOUBLE PRECISION, đơn vị VND, luôn có CHECK (amount >= 0).
 *    (Không dùng NUMERIC vì driver pg trả về string, gây vỡ logic JS.)
 *    Boolean: INTEGER với CHECK IN (0, 1).
 *
 * 4. Enum: TEXT + CHECK IN (...) TẠI DATABASE — không chỉ validate ở service.
 *    Giá trị enum phải đồng bộ với const trong service tương ứng.
 *
 * 5. CHÍNH SÁCH KHÓA NGOẠI (áp dụng đồng nhất):
 *    - Dữ liệu "sở hữu" (owned children)      -> ON DELETE CASCADE
 *    - Tham chiếu "tùy chọn" (optional refs)   -> ON DELETE SET NULL
 *    - Phạm vi tenant (center_id)             -> ON DELETE RESTRICT
 *    - audit_logs / *_history: CỐ TÌNH không đặt FK — append-only, bất tử.
 *
 * 6. Mọi ràng buộc đều ĐẶT TÊN (CONSTRAINT fk_... / chk_...) để lỗi DB trả về
 *    có thể truy vết, và để validateSchema() kiểm tra được.
 *
 * 7. Trigger viết bằng PL/pgSQL, dạng BEFORE UPDATE sửa trực tiếp NEW —
 *    sạch hơn SQLite (không cần inner UPDATE, không lo trigger kích chéo).
 *    Mỗi bảng CHỈ CÓ ĐÚNG 1 trigger maintain (bài học từ bản SQLite).
 *
 * 8. TABLE_DOCS bên dưới là DATA DICTIONARY sống: tài liệu cho từng bảng/cột,
 *    được kiểm tra bởi schema.test.ts (mọi bảng trong DB đều phải có mặt).
 * =================================================================================== */

import type { Db } from './pg-compat';

/**
 * Phiên bản schema PostgreSQL — đánh số lại từ 1 (baseline PG).
 * Không liên quan đến dãy version của SQLite cũ.
 */
export const SCHEMA_VERSION = 1;

export interface ColumnDoc {
  description: string;
}
export interface TableDoc {
  description: string;
  columns: Record<string, string>;
}


export const TABLE_DOCS: Record<string, TableDoc> = {
  users: {
    description: 'Tài khoản đăng nhập của nhân sự (admin/staff/teacher) và superadmin hệ thống.',
    columns: {
      id: 'Khóa chính.',
      username: 'Tên đăng nhập, duy nhất toàn hệ thống.',
      password_hash: 'Mật khẩu đã băm bcrypt — không bao giờ lưu plaintext.',
      role: "Vai trò: 'superadmin' | 'admin' | 'staff' | 'teacher'.",
      name: 'Tên hiển thị.',
      center_id: 'Trung tâm trực thuộc; NULL = superadmin (thấy toàn hệ thống). RESTRICT khi xóa center.',
      teacher_id: 'Liên kết tới hồ sơ giáo viên (nếu role=teacher). SET NULL khi xóa giáo viên.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  centers: {
    description: 'Trung tâm (tenant) trong mô hình SaaS multi-tenant.',
    columns: {
      id: 'Khóa chính.',
      name: 'Tên trung tâm.',
      subdomain: 'Subdomain duy nhất (vd: demo).',
      phone: 'Số điện thoại liên hệ.',
      address: 'Địa chỉ.',
      plan: "Gói cước: 'basic' (199k) | 'standard' (399k) | 'premium' (799k).",
      plan_expires_at: 'Ngày hết hạn gói (ISO date).',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  center_settings: {
    description: 'Cấu hình key-value theo từng trung tâm (ghi đè settings toàn cục).',
    columns: {
      center_id: 'Trung tâm sở hữu. CASCADE khi xóa center.',
      key: 'Khóa cấu hình.',
      value: 'Giá trị (chuỗi; JSON nếu phức tạp).',
    },
  },
  teachers: {
    description: 'Hồ sơ giáo viên của trung tâm.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm trực thuộc. RESTRICT khi xóa center.',
      name: 'Họ tên.',
      phone: 'Số điện thoại.',
      email: 'Email.',
      subject: 'Môn dạy chính.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  students: {
    description: 'Hồ sơ học viên — thực thể trung tâm của nghiệp vụ.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm trực thuộc. RESTRICT khi xóa center.',
      code: 'Mã học viên, duy nhất (vd: HV001).',
      name: 'Họ tên.',
      phone: 'Số điện thoại.',
      email: 'Email.',
      dob: 'Ngày sinh (ISO date).',
      address: 'Địa chỉ.',
      status: "Trạng thái: 'studying' | 'paused' | 'quit'.",
      note: 'Ghi chú nội bộ.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
      version: 'Phiên bản optimistic locking — tăng tự động mỗi lần UPDATE.',
    },
  },
  classes: {
    description: 'Lớp học: nhóm học viên + giáo viên + lịch học + học phí.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm sở hữu. RESTRICT khi xóa center.',
      name: 'Tên lớp.',
      teacher_id: 'Giáo viên phụ trách. SET NULL khi xóa giáo viên.',
      room_id: 'Phòng học. SET NULL khi xóa phòng.',
      schedule: 'Lịch học dạng JSON [{day, start, end}].',
      start_date: 'Ngày khai giảng (ISO date).',
      end_date: 'Ngày kết thúc (ISO date).',
      tuition_fee: 'Học phí/khóa (VND, >= 0).',
      max_students: 'Sĩ số tối đa (> 0).',
      status: "Trạng thái: 'active' | 'inactive'.",
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
      version: 'Phiên bản optimistic locking — tăng tự động mỗi lần UPDATE.',
    },
  },
  enrollments: {
    description: 'Ghi danh: học viên tham gia lớp (quan hệ nhiều-nhiều + trạng thái).',
    columns: {
      id: 'Khóa chính.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      class_id: 'Lớp học. CASCADE khi xóa lớp.',
      enrolled_at: 'Thời điểm ghi danh (UTC).',
      status: "Trạng thái: 'active' | 'inactive'.",
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  sessions: {
    description: 'Buổi học cụ thể của lớp (sinh tự động từ lịch).',
    columns: {
      id: 'Khóa chính.',
      class_id: 'Lớp học. CASCADE khi xóa lớp.',
      date: 'Ngày học (ISO date). Duy nhất theo từng lớp.',
      topic: 'Chủ đề buổi học.',
      checkin_code: 'Mã điểm danh 6 số cho giáo viên.',
      checkin_date: 'Ngày mã có hiệu lực.',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  attendance: {
    description: 'Điểm danh từng học viên trong từng buổi học.',
    columns: {
      id: 'Khóa chính.',
      session_id: 'Buổi học. CASCADE khi xóa buổi.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      status: "Trạng thái: 'present' | 'absent' | 'late'.",
      note: 'Ghi chú.',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  invoices: {
    description: 'Hóa đơn học phí của học viên.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm sở hữu. RESTRICT khi xóa center.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      class_id: 'Lớp áp dụng (tùy chọn). SET NULL khi xóa lớp.',
      amount: 'Tổng tiền hóa đơn (VND, >= 0).',
      due_date: 'Hạn thanh toán (ISO date).',
      status: "Trạng thái: 'unpaid' | 'partial' | 'paid' — tự động tính lại bởi recalcInvoiceStatus.",
      note: 'Ghi chú.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
      version: 'Phiên bản optimistic locking — tăng tự động mỗi lần UPDATE.',
    },
  },
  payments: {
    description: 'Khoản thu tiền cho hóa đơn (kể cả khoản chờ duyệt của phụ huynh).',
    columns: {
      id: 'Khóa chính.',
      invoice_id: 'Hóa đơn. CASCADE khi xóa hóa đơn.',
      amount: 'Số tiền thu (VND, > 0).',
      paid_at: 'Thời điểm thu (UTC).',
      method: 'Hình thức thu (tự do: Tiền mặt, bank_transfer, vnpay...).',
      note: 'Ghi chú.',
      status: "Trạng thái: 'pending' (chờ duyệt) | 'confirmed' | 'rejected'. Chỉ 'confirmed' được tính công nợ.",
      updated_at: 'Tự động cập nhật bởi trigger.',
      version: 'Phiên bản optimistic locking — tăng tự động mỗi lần UPDATE.',
    },
  },
  payment_txns: {
    description: 'Giao dịch thanh toán online (VNPay/VietQR) — chống trùng bằng ref.',
    columns: {
      ref: 'Mã tham chiếu duy nhất của cổng thanh toán.',
      invoice_id: 'Hóa đơn liên quan. CASCADE khi xóa hóa đơn.',
      amount: 'Số tiền (VND, > 0).',
      status: "Trạng thái: 'pending' | 'confirmed' | 'failed' | 'rejected'.",
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Cập nhật thủ công bởi service (không có trigger tự động).',
    },
  },
  settings: {
    description: 'Cấu hình key-value toàn cục (legacy — mới dùng center_settings).',
    columns: {
      key: 'Khóa cấu hình (PK).',
      value: 'Giá trị.',
    },
  },
  reminders: {
    description: 'Lịch sử nhắc học phí qua Zalo (ZNS).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm gửi. RESTRICT khi xóa center.',
      invoice_id: 'Hóa đơn liên quan (tùy chọn). SET NULL khi xóa hóa đơn.',
      student_id: 'Học viên (tùy chọn). SET NULL khi xóa học viên.',
      phone: 'SĐT người nhận.',
      kind: "Loại nhắc: 'overdue' | 'upcoming' | 'receipt'.",
      status: "Kết quả gửi: 'sent' | 'failed' | 'demo' (chế độ demo/log).",
      message: 'Nội dung đã gửi.',
      response: 'Phản hồi từ Zalo API.',
      created_at: 'Thời điểm gửi (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  parents: {
    description: 'Tài khoản phụ huynh (đăng nhập bằng SĐT + mật khẩu riêng).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm trực thuộc. RESTRICT khi xóa center.',
      phone: 'SĐT đăng nhập. Duy nhất trong từng center.',
      password_hash: 'Mật khẩu đã băm bcrypt.',
      name: 'Tên phụ huynh.',
      referral_code: 'Mã giới thiệu duy nhất của phụ huynh.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  parent_students: {
    description: 'Liên kết phụ huynh — con (một phụ huynh nhiều con, một con nhiều phụ huynh).',
    columns: {
      parent_id: 'Phụ huynh. CASCADE khi xóa phụ huynh.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      created_at: 'Thời điểm liên kết (UTC).',
      updated_at: 'Cập nhật thủ công bởi service (không có trigger tự động).',
    },
  },
  leave_requests: {
    description: 'Đơn xin nghỉ phép của học viên (phụ huynh gửi, trung tâm duyệt).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      student_id: 'Học viên xin nghỉ. CASCADE khi xóa học viên.',
      class_id: 'Lớp liên quan (tùy chọn). SET NULL khi xóa lớp.',
      from_date: 'Nghỉ từ ngày (ISO date).',
      to_date: 'Nghỉ đến ngày (ISO date) — phải >= from_date.',
      reason: 'Lý do.',
      status: "Trạng thái: 'pending' | 'approved' | 'rejected'.",
      decided_by: 'Người duyệt (users.id). SET NULL khi xóa user.',
      decided_at: 'Thời điểm duyệt (UTC).',
      created_at: 'Thời điểm gửi đơn (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  grades: {
    description: 'Sổ điểm điện tử: điểm từng đầu điểm của học viên.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      class_id: 'Lớp (tùy chọn). SET NULL khi xóa lớp.',
      title: 'Tên đầu điểm (vd: Kiểm tra giữa kỳ).',
      score: 'Điểm đạt được (>= 0, <= max_score).',
      max_score: 'Thang điểm (> 0, mặc định 10).',
      comment: 'Nhận xét.',
      created_by: 'Người nhập điểm (users.id). SET NULL khi xóa user.',
      created_at: 'Thời điểm nhập (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  homework: {
    description: 'Bài tập / quiz giao cho lớp (học từ Google Classroom: draft/schedule/rubric).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      class_id: 'Lớp được giao. CASCADE khi xóa lớp.',
      title: 'Tiêu đề.',
      content: 'Nội dung (hỗ trợ rich text).',
      due_date: 'Hạn nộp (ISO datetime).',
      status: "Trạng thái: 'draft' | 'scheduled' (hẹn giờ) | 'published'.",
      publish_at: 'Thời điểm tự đăng khi status=scheduled.',
      max_score: 'Điểm tối đa (NULL = không chấm điểm).',
      close_date: 'Hạn chót cứng — qua ngày này khóa nộp bài.',
      kind: "Loại: 'homework' (tự luận/nộp file) | 'quiz' (trắc nghiệm tự chấm).",
      rubric_id: 'Rubric chấm điểm (tùy chọn). SET NULL khi xóa rubric.',
      created_by: 'Người tạo (users.id). SET NULL khi xóa user.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
      version: 'Phiên bản optimistic locking — tăng tự động mỗi lần UPDATE.',
    },
  },
  homework_completions: {
    description: 'Đánh dấu hoàn thành bài tập theo từng học viên.',
    columns: {
      id: 'Khóa chính.',
      homework_id: 'Bài tập. CASCADE khi xóa bài.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      completed_at: 'Thời điểm hoàn thành (UTC).',
      completed_by: "Người đánh dấu: 'parent' | 'teacher' | 'student'.",
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  homework_attachments: {
    description: 'Tài liệu đính kèm của bài tập (file/link/audio/video).',
    columns: {
      id: 'Khóa chính.',
      homework_id: 'Bài tập. CASCADE khi xóa bài.',
      name: 'Tên hiển thị.',
      url: 'Đường dẫn file hoặc link.',
      kind: "Loại: 'link' | 'file' | 'audio' | 'video'.",
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  homework_targets: {
    description: 'Giao bài riêng cho từng học viên (Classroom: individual students). Rỗng = cả lớp.',
    columns: {
      homework_id: 'Bài tập. CASCADE khi xóa bài.',
      student_id: 'Học viên được giao riêng. CASCADE khi xóa học viên.',
      due_date: 'Hạn riêng cho học viên này (Canvas: differentiated deadlines).',
      updated_at: 'Cập nhật thủ công bởi service (không có trigger tự động).',
    },
  },
  rubrics: {
    description: 'Bộ tiêu chí chấm điểm tái sử dụng.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      name: 'Tên rubric.',
      created_by: 'Người tạo (users.id). SET NULL khi xóa user.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  rubric_criteria: {
    description: 'Từng tiêu chí trong rubric.',
    columns: {
      id: 'Khóa chính.',
      rubric_id: 'Rubric chứa. CASCADE khi xóa rubric.',
      name: 'Tên tiêu chí.',
      max_score: 'Điểm tối đa của tiêu chí (> 0).',
      position: 'Thứ tự hiển thị (>= 0).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  quiz_questions: {
    description: 'Câu hỏi trắc nghiệm của quiz.',
    columns: {
      id: 'Khóa chính.',
      homework_id: 'Quiz chứa (homework.kind=quiz). CASCADE khi xóa bài.',
      position: 'Thứ tự câu hỏi (>= 0).',
      question: 'Nội dung câu hỏi.',
      points: 'Số điểm của câu (> 0).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  quiz_options: {
    description: 'Các đáp án của một câu hỏi trắc nghiệm.',
    columns: {
      id: 'Khóa chính.',
      question_id: 'Câu hỏi. CASCADE khi xóa câu hỏi.',
      position: 'Thứ tự đáp án (>= 0).',
      text: 'Nội dung đáp án.',
      is_correct: '1 = đáp án đúng, 0 = sai.',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  quiz_attempts: {
    description: 'Lượt làm quiz của học viên.',
    columns: {
      id: 'Khóa chính.',
      homework_id: 'Quiz. CASCADE khi xóa bài.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      score: 'Điểm đạt được (>= 0).',
      max_score: 'Tổng điểm của quiz (>= 0).',
      submitted_at: 'Thời điểm nộp (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  quiz_answers: {
    description: 'Đáp án học viên đã chọn trong từng lượt làm quiz.',
    columns: {
      attempt_id: 'Lượt làm. CASCADE khi xóa lượt.',
      question_id: 'Câu hỏi. CASCADE khi xóa câu hỏi.',
      option_id: 'Đáp án đã chọn (NULL = bỏ trống). SET NULL khi xóa đáp án.',
    },
  },
  homework_scores: {
    description: 'Điểm bài tập thường (chấm tay hoặc theo rubric) theo từng học viên.',
    columns: {
      homework_id: 'Bài tập. CASCADE khi xóa bài.',
      student_id: 'Học viên. CASCADE khi xóa học viên.',
      score: 'Điểm (>= 0, NULL = chưa chấm).',
      feedback: 'Nhận xét của giáo viên.',
      graded_at: 'Thời điểm chấm (UTC).',
      graded_by: 'Người chấm (users.id). SET NULL khi xóa user.',
      updated_at: 'Cập nhật thủ công bởi service (không có trigger tự động).',
    },
  },
  rooms: {
    description: 'Phòng học của trung tâm (chặn trùng lịch khi xếp lớp).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      name: 'Tên phòng.',
      capacity: 'Sức chứa (> 0).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  salary_rules: {
    description: 'Quy tắc lương theo buổi của từng giáo viên.',
    columns: {
      teacher_id: 'Giáo viên (PK). CASCADE khi xóa giáo viên.',
      per_session_amount: 'Tiền công mỗi buổi dạy (VND, >= 0).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  teacher_checkins: {
    description: 'Giáo viên điểm danh buổi dạy bằng mã 6 số.',
    columns: {
      id: 'Khóa chính.',
      session_id: 'Buổi dạy. CASCADE khi xóa buổi.',
      teacher_id: 'Giáo viên. CASCADE khi xóa giáo viên.',
      created_at: 'Thời điểm điểm danh (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  trial_registrations: {
    description: 'Đăng ký học thử từ landing page.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      name: 'Tên người đăng ký.',
      phone: 'SĐT.',
      class_id: 'Lớp muốn học thử (tùy chọn). SET NULL khi xóa lớp.',
      desired_date: 'Ngày mong muốn (ISO date).',
      note: 'Ghi chú.',
      referral_code: 'Mã giới thiệu được dùng (nếu có).',
      status: "Trạng thái: 'new' | 'contacted' | 'converted'.",
      created_at: 'Thời điểm đăng ký (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  leads: {
    description: 'Lead mini-CRM: khách hàng tiềm năng và pipeline chăm sóc.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      name: 'Tên lead.',
      phone: 'SĐT.',
      source: 'Nguồn (vd: landing, facebook, referral).',
      status: "Trạng thái pipeline: 'new' | 'contacted' | 'trial' | 'enrolled' | 'lost'.",
      note: 'Ghi chú chăm sóc.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  referrals: {
    description: 'Lịch sử giới thiệu bạn bè của phụ huynh (đổi credit học phí).',
    columns: {
      id: 'Khóa chính.',
      referrer_parent_id: 'Phụ huynh giới thiệu. CASCADE khi xóa phụ huynh.',
      referred_phone: 'SĐT người được giới thiệu.',
      referred_student_id: 'Học viên đã đăng ký từ giới thiệu (tùy chọn). SET NULL khi xóa học viên.',
      status: "Trạng thái: 'pending' | 'rewarded'.",
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  credits: {
    description: 'Credit học phí của phụ huynh (từ giới thiệu / khuyến mãi), trừ dần khi đóng tiền.',
    columns: {
      id: 'Khóa chính.',
      parent_id: 'Phụ huynh sở hữu. CASCADE khi xóa phụ huynh.',
      amount: 'Tổng credit được cấp (VND, > 0).',
      reason: 'Lý do cấp.',
      used_amount: 'Đã sử dụng (0 <= used_amount <= amount).',
      created_at: 'Thời điểm cấp (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  reviews: {
    description: 'Đánh giá của phụ huynh về trung tâm (duyệt mới hiển thị công khai).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm được đánh giá. RESTRICT khi xóa center.',
      parent_id: 'Phụ huynh đánh giá (tùy chọn). SET NULL khi xóa phụ huynh.',
      rating: 'Số sao (1–5).',
      comment: 'Nội dung đánh giá.',
      status: "Trạng thái: 'pending' | 'approved' | 'rejected'.",
      created_at: 'Thời điểm đánh giá (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  audit_logs: {
    description:
      'Nhật ký kiểm toán append-only: mọi thao tác quan trọng của người dùng. ' +
      'CỐ TÌNH không đặt khóa ngoại để log bất tử kể cả khi bản ghi gốc bị xóa.',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm nơi xảy ra thao tác (có thể NULL).',
      actor_id: 'ID người thực hiện (không FK — giữ log khi user bị xóa).',
      actor_name: 'Tên người thực hiện (denormalize để log tự đủ nghĩa).',
      actor_role: 'Vai trò lúc thực hiện.',
      action: 'Hành động (vd: student.delete, payment.approve).',
      entity: 'Loại đối tượng (vd: student, invoice).',
      entity_id: 'ID đối tượng (không FK — giữ log khi đối tượng bị xóa).',
      summary: 'Mô tả ngắn gọn cho người đọc.',
      meta: 'Chi tiết thêm dạng JSON.',
      ip: 'IP của người thực hiện.',
      created_at: 'Thời điểm ghi log (UTC).',
    },
  },
  question_bank: {
    description: 'Ngân hàng câu hỏi trắc nghiệm tái sử dụng (học từ Canvas/Moodle).',
    columns: {
      id: 'Khóa chính.',
      center_id: 'Trung tâm. RESTRICT khi xóa center.',
      tag: 'Nhãn/chủ đề để tìm nhanh.',
      question: 'Nội dung câu hỏi.',
      points: 'Số điểm mặc định khi đưa vào quiz (> 0).',
      created_by: 'Người tạo (users.id). SET NULL khi xóa user.',
      created_at: 'Thời điểm tạo (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  question_bank_options: {
    description: 'Các đáp án của câu hỏi trong ngân hàng.',
    columns: {
      id: 'Khóa chính.',
      question_id: 'Câu hỏi. CASCADE khi xóa câu hỏi.',
      position: 'Thứ tự đáp án (>= 0).',
      text: 'Nội dung đáp án.',
      is_correct: '1 = đáp án đúng, 0 = sai.',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  homework_submissions: {
    description: 'Bài nộp của học viên: ảnh/file bài làm + ghi chú (khóa nộp khi quá close_date).',
    columns: {
      id: 'Khóa chính.',
      homework_id: 'Bài tập. CASCADE khi xóa bài.',
      student_id: 'Học viên nộp. CASCADE khi xóa học viên.',
      file_url: 'Đường dẫn file đã tải lên (tối đa 10MB).',
      file_name: 'Tên file gốc.',
      note: 'Ghi chú kèm theo.',
      submitted_at: 'Thời điểm nộp (UTC).',
      updated_at: 'Tự động cập nhật bởi trigger.',
    },
  },
  payment_history: {
    description:
      'Lịch sử BẤT BIẾN của payments: mọi INSERT/UPDATE/DELETE đều được trigger ' +
      'ghi snapshot JSON. Append-only, không FK về payments để dấu vết tồn tại ' +
      'kể cả khi payment gốc bị xóa.',
    columns: {
      id: 'Khóa chính.',
      payment_id: 'ID payment tại thời điểm ghi (không FK — cố tình).',
      action: "Hành động: 'insert' | 'update' | 'delete'.",
      old_data: 'Snapshot JSON trước thay đổi (NULL khi insert).',
      new_data: 'Snapshot JSON sau thay đổi (NULL khi delete).',
      changed_by: 'Người thực hiện — NULL vì trigger không biết user app (xem audit_logs).',
      changed_at: 'Thời điểm ghi (UTC).',
    },
  },
  invoice_history: {
    description:
      'Lịch sử BẤT BIẾN của invoices: mọi INSERT/UPDATE/DELETE đều được trigger ' +
      'ghi snapshot JSON. Append-only, không FK về invoices.',
    columns: {
      id: 'Khóa chính.',
      invoice_id: 'ID invoice tại thời điểm ghi (không FK — cố tình).',
      action: "Hành động: 'insert' | 'update' | 'delete'.",
      old_data: 'Snapshot JSON trước thay đổi (NULL khi insert).',
      new_data: 'Snapshot JSON sau thay đổi (NULL khi delete).',
      changed_by: 'Người thực hiện — NULL vì trigger không biết user app (xem audit_logs).',
      changed_at: 'Thời điểm ghi (UTC).',
    },
  },
};

/* -------------------------------------------------------------------------------------
 * createSchema — tạo toàn bộ bảng (idempotent — IF NOT EXISTS).
 * PostgreSQL baseline: DB mới nhận đầy đủ FK + CHECK + trigger + view.
 * Không còn khái niệm 'DB cũ SQLite' — migration SQLite->PG là script riêng
 * (xem scripts/migrate-sqlite-to-pg.ts).
 * ----------------------------------------------------------------------------------- */
export async function createSchema(db: Db): Promise<void> {
  await db.exec(`

-- ================= BẢNG NỀN TẢNG =================
CREATE TABLE IF NOT EXISTS centers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subdomain TEXT UNIQUE,
  phone TEXT,
  address TEXT,
  plan TEXT NOT NULL DEFAULT 'standard'
    CONSTRAINT chk_centers_plan CHECK (plan IN ('basic', 'standard', 'premium')),
  plan_expires_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= NHÂN SỰ & ĐÀO TẠO =================
-- teachers tạo TRƯỚC users vì users.teacher_id REFERENCES teachers(id)
CREATE TABLE IF NOT EXISTS teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_teachers_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  subject TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'staff'
    CONSTRAINT chk_users_role CHECK (role IN ('superadmin', 'admin', 'staff', 'teacher')),
  name TEXT NOT NULL,
  center_id INTEGER
    CONSTRAINT fk_users_center REFERENCES centers(id) ON DELETE RESTRICT,
  teacher_id INTEGER
    CONSTRAINT fk_users_teacher REFERENCES teachers(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS center_settings (
  center_id INTEGER NOT NULL
    CONSTRAINT fk_center_settings_center REFERENCES centers(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT,
  PRIMARY KEY (center_id, key)
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);


CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_students_center REFERENCES centers(id) ON DELETE RESTRICT,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  dob TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'studying'
    CONSTRAINT chk_students_status CHECK (status IN ('studying', 'paused', 'quit')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_rooms_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 30
    CONSTRAINT chk_rooms_capacity CHECK (capacity > 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_classes_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  teacher_id INTEGER
    CONSTRAINT fk_classes_teacher REFERENCES teachers(id) ON DELETE SET NULL,
  room_id INTEGER
    CONSTRAINT fk_classes_room REFERENCES rooms(id) ON DELETE SET NULL,
  schedule TEXT NOT NULL DEFAULT '[]',
  start_date TEXT,
  end_date TEXT,
  tuition_fee DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_classes_fee CHECK (tuition_fee >= 0),
  max_students INTEGER NOT NULL DEFAULT 30
    CONSTRAINT chk_classes_max CHECK (max_students > 0),
  status TEXT NOT NULL DEFAULT 'active'
    CONSTRAINT chk_classes_status CHECK (status IN ('active', 'inactive')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_enrollments_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_enrollments_class REFERENCES classes(id) ON DELETE CASCADE,
  enrolled_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  status TEXT NOT NULL DEFAULT 'active'
    CONSTRAINT chk_enrollments_status CHECK (status IN ('active', 'inactive')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(student_id, class_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_sessions_class REFERENCES classes(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  topic TEXT,
  checkin_code TEXT,
  checkin_date TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(class_id, date)
);

CREATE TABLE IF NOT EXISTS attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL
    CONSTRAINT fk_attendance_session REFERENCES sessions(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_attendance_student REFERENCES students(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'present'
    CONSTRAINT chk_attendance_status CHECK (status IN ('present', 'absent', 'late')),
  note TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(session_id, student_id)
);

CREATE TABLE IF NOT EXISTS teacher_checkins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL
    CONSTRAINT fk_checkins_session REFERENCES sessions(id) ON DELETE CASCADE,
  teacher_id INTEGER NOT NULL
    CONSTRAINT fk_checkins_teacher REFERENCES teachers(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(session_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS salary_rules (
  teacher_id INTEGER PRIMARY KEY
    CONSTRAINT fk_salary_teacher REFERENCES teachers(id) ON DELETE CASCADE,
  per_session_amount DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_salary_amount CHECK (per_session_amount >= 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= TÀI CHÍNH =================
CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_invoices_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_invoices_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_invoices_class REFERENCES classes(id) ON DELETE SET NULL,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_invoices_amount CHECK (amount >= 0),
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'unpaid'
    CONSTRAINT chk_invoices_status CHECK (status IN ('unpaid', 'partial', 'paid')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL
    CONSTRAINT fk_payments_invoice REFERENCES invoices(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
  paid_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  method TEXT,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'confirmed'
    CONSTRAINT chk_payments_status CHECK (status IN ('pending', 'confirmed', 'rejected')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payment_txns (
  ref TEXT PRIMARY KEY,
  invoice_id INTEGER NOT NULL
    CONSTRAINT fk_txns_invoice REFERENCES invoices(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_txns_amount CHECK (amount > 0),
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_txns_status CHECK (status IN ('pending', 'confirmed', 'failed', 'rejected')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS parents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_parents_center REFERENCES centers(id) ON DELETE RESTRICT,
  phone TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  referral_code TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(center_id, phone)
);

CREATE TABLE IF NOT EXISTS parent_students (
  parent_id INTEGER NOT NULL
    CONSTRAINT fk_ps_parent REFERENCES parents(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_ps_student REFERENCES students(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (parent_id, student_id)
);

CREATE TABLE IF NOT EXISTS credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id INTEGER NOT NULL
    CONSTRAINT fk_credits_parent REFERENCES parents(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_credits_amount CHECK (amount > 0),
  reason TEXT,
  used_amount DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_credits_used CHECK (used_amount >= 0),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT chk_credits_used_lte CHECK (used_amount <= amount)
);

-- ================= CỔNG PHỤ HUYNH =================

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_leaves_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_leaves_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_leaves_class REFERENCES classes(id) ON DELETE SET NULL,
  from_date TEXT NOT NULL,
  to_date TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_leaves_status CHECK (status IN ('pending', 'approved', 'rejected')),
  decided_by INTEGER
    CONSTRAINT fk_leaves_decider REFERENCES users(id) ON DELETE SET NULL,
  decided_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT chk_leaves_dates CHECK (to_date >= from_date)
);

CREATE TABLE IF NOT EXISTS grades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_grades_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_grades_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_grades_class REFERENCES classes(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  score DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_grades_score CHECK (score >= 0),
  max_score DOUBLE PRECISION NOT NULL DEFAULT 10
    CONSTRAINT chk_grades_max CHECK (max_score > 0),
  comment TEXT,
  created_by INTEGER
    CONSTRAINT fk_grades_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT chk_grades_score_lte CHECK (score <= max_score)
);

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_reviews_center REFERENCES centers(id) ON DELETE RESTRICT,
  parent_id INTEGER
    CONSTRAINT fk_reviews_parent REFERENCES parents(id) ON DELETE SET NULL,
  rating INTEGER NOT NULL
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_reviews_status CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS referrals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_parent_id INTEGER NOT NULL
    CONSTRAINT fk_referrals_referrer REFERENCES parents(id) ON DELETE CASCADE,
  referred_phone TEXT,
  referred_student_id INTEGER
    CONSTRAINT fk_referrals_student REFERENCES students(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_referrals_status CHECK (status IN ('pending', 'rewarded')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= BÀI TẬP / QUIZ =================
CREATE TABLE IF NOT EXISTS rubrics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_rubrics_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  created_by INTEGER
    CONSTRAINT fk_rubrics_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rubric_criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rubric_id INTEGER NOT NULL
    CONSTRAINT fk_criteria_rubric REFERENCES rubrics(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  max_score DOUBLE PRECISION NOT NULL DEFAULT 10
    CONSTRAINT chk_criteria_max CHECK (max_score > 0),
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_criteria_pos CHECK (position >= 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS homework (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_homework_center REFERENCES centers(id) ON DELETE RESTRICT,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_homework_class REFERENCES classes(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'published'
    CONSTRAINT chk_homework_status CHECK (status IN ('draft', 'scheduled', 'published')),
  publish_at TEXT,
  max_score DOUBLE PRECISION
    CONSTRAINT chk_homework_max CHECK (max_score IS NULL OR max_score > 0),
  close_date TEXT,
  kind TEXT NOT NULL DEFAULT 'homework'
    CONSTRAINT chk_homework_kind CHECK (kind IN ('homework', 'quiz')),
  rubric_id INTEGER
    CONSTRAINT fk_homework_rubric REFERENCES rubrics(id) ON DELETE SET NULL,
  created_by INTEGER
    CONSTRAINT fk_homework_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS homework_attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_attachments_hw REFERENCES homework(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'link'
    CONSTRAINT chk_attachments_kind CHECK (kind IN ('link', 'file', 'audio', 'video')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS homework_targets (
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_targets_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_targets_student REFERENCES students(id) ON DELETE CASCADE,
  due_date TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_completions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_completions_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_completions_student REFERENCES students(id) ON DELETE CASCADE,
  completed_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  completed_by TEXT NOT NULL DEFAULT 'parent'
    CONSTRAINT chk_completions_by CHECK (completed_by IN ('parent', 'teacher', 'student')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_scores (
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_scores_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_scores_student REFERENCES students(id) ON DELETE CASCADE,
  score DOUBLE PRECISION
    CONSTRAINT chk_scores_value CHECK (score IS NULL OR score >= 0),
  feedback TEXT,
  graded_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  graded_by INTEGER
    CONSTRAINT fk_scores_grader REFERENCES users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_submissions_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_submissions_student REFERENCES students(id) ON DELETE CASCADE,
  file_url TEXT,
  file_name TEXT,
  note TEXT,
  submitted_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_qq_hw REFERENCES homework(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qq_pos CHECK (position >= 0),
  question TEXT NOT NULL,
  points DOUBLE PRECISION NOT NULL DEFAULT 1
    CONSTRAINT chk_qq_points CHECK (points > 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qo_question REFERENCES quiz_questions(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qo_pos CHECK (position >= 0),
  text TEXT NOT NULL,
  is_correct INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qo_correct CHECK (is_correct IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_qa_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_qa_student REFERENCES students(id) ON DELETE CASCADE,
  score DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_qa_score CHECK (score >= 0),
  max_score DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_qa_max CHECK (max_score >= 0),
  submitted_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_answers (
  attempt_id INTEGER NOT NULL
    CONSTRAINT fk_qans_attempt REFERENCES quiz_attempts(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qans_question REFERENCES quiz_questions(id) ON DELETE CASCADE,
  option_id INTEGER
    CONSTRAINT fk_qans_option REFERENCES quiz_options(id) ON DELETE SET NULL,
  UNIQUE(attempt_id, question_id)
);

CREATE TABLE IF NOT EXISTS question_bank (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_qbank_center REFERENCES centers(id) ON DELETE RESTRICT,
  tag TEXT,
  question TEXT NOT NULL,
  points DOUBLE PRECISION NOT NULL DEFAULT 1
    CONSTRAINT chk_qbank_points CHECK (points > 0),
  created_by INTEGER
    CONSTRAINT fk_qbank_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS question_bank_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qbo_question REFERENCES question_bank(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qbo_pos CHECK (position >= 0),
  text TEXT NOT NULL,
  is_correct INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qbo_correct CHECK (is_correct IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= TUYỂN SINH & TĂNG TRƯỞNG =================
CREATE TABLE IF NOT EXISTS trial_registrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_trials_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  class_id INTEGER
    CONSTRAINT fk_trials_class REFERENCES classes(id) ON DELETE SET NULL,
  desired_date TEXT,
  note TEXT,
  referral_code TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CONSTRAINT chk_trials_status CHECK (status IN ('new', 'contacted', 'converted')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_leads_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  source TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CONSTRAINT chk_leads_status CHECK (status IN ('new', 'contacted', 'trial', 'enrolled', 'lost')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= VẬN HÀNH =================
CREATE TABLE IF NOT EXISTS reminders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_reminders_center REFERENCES centers(id) ON DELETE RESTRICT,
  invoice_id INTEGER
    CONSTRAINT fk_reminders_invoice REFERENCES invoices(id) ON DELETE SET NULL,
  student_id INTEGER
    CONSTRAINT fk_reminders_student REFERENCES students(id) ON DELETE SET NULL,
  phone TEXT,
  kind TEXT NOT NULL DEFAULT 'overdue'
    CONSTRAINT chk_reminders_kind CHECK (kind IN ('overdue', 'upcoming', 'receipt')),
  status TEXT NOT NULL DEFAULT 'sent'
    CONSTRAINT chk_reminders_status CHECK (status IN ('sent', 'failed', 'demo')),
  message TEXT,
  response TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER,
  actor_id INTEGER,
  actor_name TEXT,
  actor_role TEXT,
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id INTEGER,
  summary TEXT NOT NULL,
  meta TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

`);
}

/* -------------------------------------------------------------------------------------
 * Trigger maintain: MỖI BẢNG CHỈ CÓ ĐÚNG 1 TRIGGER (BEFORE UPDATE, sửa trực tiếp NEW).
 * PL/pgSQL cho phép gán NEW.column trong BEFORE trigger — sạch và an toàn hơn
 * hẳn cách inner-UPDATE của SQLite (không bao giờ có chuyện trigger kích chéo).
 * ----------------------------------------------------------------------------------- */
const MAINTAIN_TABLES = [
  'users',
  'centers',
  'teachers',
  'students',
  'rooms',
  'classes',
  'enrollments',
  'sessions',
  'attendance',
  'teacher_checkins',
  'credits',
  'parents',
  'leave_requests',
  'grades',
  'reviews',
  'referrals',
  'rubrics',
  'rubric_criteria',
  'homework',
  'homework_attachments',
  'homework_completions',
  'homework_submissions',
  'quiz_questions',
  'quiz_options',
  'quiz_attempts',
  'question_bank',
  'question_bank_options',
  'trial_registrations',
  'leads',
  'reminders',
] as const;

/** Bảng có optimistic locking (cột version). */
const VERSIONED_TABLES = ['invoices', 'payments', 'students', 'classes', 'homework'] as const;

const TS_EXPR = `to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')`;

export async function createTriggers(db: Db): Promise<void> {
  await db.exec(`
CREATE OR REPLACE FUNCTION maintain_row() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
    NEW.updated_at := ${TS_EXPR};
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION maintain_row_versioned() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
    NEW.updated_at := ${TS_EXPR};
  END IF;
  IF NEW.version IS NULL OR NEW.version = OLD.version THEN
    NEW.version := OLD.version + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
`);
  // payments/invoices do createHistoryTables() đảm nhiệm (trigger audit gộp maintain)
  for (const t of MAINTAIN_TABLES) {
    const versioned = (VERSIONED_TABLES as readonly string[]).includes(t);
    const fn = versioned ? 'maintain_row_versioned()' : 'maintain_row()';
    await db.exec(`
DROP TRIGGER IF EXISTS trg_${t}_maintain ON ${t};
CREATE TRIGGER trg_${t}_maintain BEFORE UPDATE ON ${t}
FOR EACH ROW EXECUTE FUNCTION ${fn};`);
  }
}

/* -------------------------------------------------------------------------------------
 * Lịch sử BẤT BIẾN của tiền bạc (immutable financial trail).
 * Như bản SQLite: mọi INSERT/UPDATE/DELETE trên payments/invoices đều được ghi
 * snapshot JSON. BEFORE trigger nên vừa ghi history vừa bảo trì
 * updated_at/version trong cùng một lần — không cần trigger riêng.
 * ----------------------------------------------------------------------------------- */
export async function createHistoryTables(db: Db): Promise<void> {
  await db.exec(`
CREATE TABLE IF NOT EXISTS payment_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id INTEGER NOT NULL,
  action TEXT NOT NULL CONSTRAINT chk_ph_action CHECK (action IN ('insert', 'update', 'delete')),
  old_data TEXT,
  new_data TEXT,
  changed_by INTEGER,
  changed_at TEXT NOT NULL DEFAULT (${TS_EXPR})
);
CREATE TABLE IF NOT EXISTS invoice_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL,
  action TEXT NOT NULL CONSTRAINT chk_ih_action CHECK (action IN ('insert', 'update', 'delete')),
  old_data TEXT,
  new_data TEXT,
  changed_by INTEGER,
  changed_at TEXT NOT NULL DEFAULT (${TS_EXPR})
);
CREATE INDEX IF NOT EXISTS idx_payment_history_payment ON payment_history(payment_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_history_invoice ON invoice_history(invoice_id, changed_at DESC);

CREATE OR REPLACE FUNCTION audit_payment() RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO payment_history (payment_id, action, new_data)
    VALUES (NEW.id, 'insert',
      json_build_object('id', NEW.id, 'invoice_id', NEW.invoice_id, 'amount', NEW.amount,
                        'status', NEW.status, 'method', NEW.method, 'paid_at', NEW.paid_at));
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO payment_history (payment_id, action, old_data, new_data)
    VALUES (NEW.id, 'update',
      json_build_object('id', OLD.id, 'invoice_id', OLD.invoice_id, 'amount', OLD.amount,
                        'status', OLD.status, 'method', OLD.method, 'paid_at', OLD.paid_at),
      json_build_object('id', NEW.id, 'invoice_id', NEW.invoice_id, 'amount', NEW.amount,
                        'status', NEW.status, 'method', NEW.method, 'paid_at', NEW.paid_at));
    IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
      NEW.updated_at := ${TS_EXPR};
    END IF;
    IF NEW.version IS NULL OR NEW.version = OLD.version THEN
      NEW.version := OLD.version + 1;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO payment_history (payment_id, action, old_data)
    VALUES (OLD.id, 'delete',
      json_build_object('id', OLD.id, 'invoice_id', OLD.invoice_id, 'amount', OLD.amount,
                        'status', OLD.status, 'method', OLD.method, 'paid_at', OLD.paid_at));
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION audit_invoice() RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO invoice_history (invoice_id, action, new_data)
    VALUES (NEW.id, 'insert',
      json_build_object('id', NEW.id, 'student_id', NEW.student_id, 'amount', NEW.amount,
                        'status', NEW.status, 'due_date', NEW.due_date));
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO invoice_history (invoice_id, action, old_data, new_data)
    VALUES (NEW.id, 'update',
      json_build_object('id', OLD.id, 'student_id', OLD.student_id, 'amount', OLD.amount,
                        'status', OLD.status, 'due_date', OLD.due_date),
      json_build_object('id', NEW.id, 'student_id', NEW.student_id, 'amount', NEW.amount,
                        'status', NEW.status, 'due_date', NEW.due_date));
    IF NEW.updated_at IS NULL OR NEW.updated_at = OLD.updated_at THEN
      NEW.updated_at := ${TS_EXPR};
    END IF;
    IF NEW.version IS NULL OR NEW.version = OLD.version THEN
      NEW.version := OLD.version + 1;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO invoice_history (invoice_id, action, old_data)
    VALUES (OLD.id, 'delete',
      json_build_object('id', OLD.id, 'student_id', OLD.student_id, 'amount', OLD.amount,
                        'status', OLD.status, 'due_date', OLD.due_date));
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_payments_audit ON payments;
CREATE TRIGGER trg_payments_audit
BEFORE INSERT OR UPDATE OR DELETE ON payments
FOR EACH ROW EXECUTE FUNCTION audit_payment();

DROP TRIGGER IF EXISTS trg_invoices_audit ON invoices;
CREATE TRIGGER trg_invoices_audit
BEFORE INSERT OR UPDATE OR DELETE ON invoices
FOR EACH ROW EXECUTE FUNCTION audit_invoice();
`);
}

/* -------------------------------------------------------------------------------------
 * View báo cáo chỉ đọc.
 * ----------------------------------------------------------------------------------- */
export async function createViews(db: Db): Promise<void> {
  await db.exec(`
CREATE OR REPLACE VIEW v_invoice_balance AS
SELECT
  i.id AS invoice_id,
  i.center_id,
  i.student_id,
  i.class_id,
  i.amount AS invoice_amount,
  i.status,
  i.due_date,
  COALESCE((
    SELECT SUM(p.amount) FROM payments p
    WHERE p.invoice_id = i.id AND p.status = 'confirmed'
  ), 0) AS paid_confirmed,
  i.amount - COALESCE((
    SELECT SUM(p.amount) FROM payments p
    WHERE p.invoice_id = i.id AND p.status = 'confirmed'
  ), 0) AS balance
FROM invoices i;
`);
}

/* -------------------------------------------------------------------------------------
 * validateSchema — tự kiểm tra tính toàn vẹn của schema trên DB hiện tại.
 * PostgreSQL tự enforce FK khi ghi nên không cần kiểm tra orphan như SQLite.
 * ----------------------------------------------------------------------------------- */
const EXPECTED_TABLES = Object.keys(TABLE_DOCS);

/** Số FK kỳ vọng cho từng bảng (0 = cố tình không đặt). */
const EXPECTED_FK_COUNT: Record<string, number> = {
  users: 2,
  centers: 0,
  center_settings: 1,
  settings: 0,
  teachers: 1,
  students: 1,
  rooms: 1,
  classes: 3,
  enrollments: 2,
  sessions: 1,
  attendance: 2,
  teacher_checkins: 2,
  salary_rules: 1,
  invoices: 3,
  payments: 1,
  payment_txns: 1,
  credits: 1,
  parents: 1,
  parent_students: 2,
  leave_requests: 4,
  grades: 4,
  reviews: 2,
  referrals: 2,
  rubrics: 2,
  rubric_criteria: 1,
  homework: 4,
  homework_attachments: 1,
  homework_targets: 2,
  homework_completions: 2,
  homework_scores: 3,
  homework_submissions: 2,
  quiz_questions: 1,
  quiz_options: 1,
  quiz_attempts: 2,
  quiz_answers: 3,
  question_bank: 2,
  question_bank_options: 1,
  trial_registrations: 2,
  leads: 1,
  reminders: 3,
  audit_logs: 0,
  payment_history: 0,
  invoice_history: 0,
};

export async function validateSchema(db: Db): Promise<void> {
  const problems: string[] = [];

  const tables = (
    (await db.query(`SELECT tablename AS name FROM pg_tables WHERE schemaname = 'public'`)).rows as {
      name: string;
    }[]
  ).map((r) => r.name);
  const existing = new Set(tables);
  for (const t of EXPECTED_TABLES) {
    if (!existing.has(t)) problems.push(`Thiếu bảng: ${t}`);
  }

  for (const [table, expected] of Object.entries(EXPECTED_FK_COUNT)) {
    if (!existing.has(table)) continue;
    const r = await db.query(
      `SELECT COUNT(*)::int AS c FROM pg_constraint WHERE conrelid = $1::regclass AND contype = 'f'`,
      [table]
    );
    const c = (r.rows[0] as { c: number }).c;
    if (c !== expected) problems.push(`Bảng ${table}: kỳ vọng ${expected} FK, thực tế ${c}`);
  }

  const trgs = (
    (await db.query(`SELECT tgname AS name FROM pg_trigger WHERE NOT tgisinternal`)).rows as {
      name: string;
    }[]
  ).map((r) => r.name);
  const tset = new Set(trgs);
  for (const t of MAINTAIN_TABLES) {
    if (!tset.has(`trg_${t}_maintain`)) problems.push(`Thiếu trigger: trg_${t}_maintain`);
  }
  for (const t of ['payments', 'invoices']) {
    if (!tset.has(`trg_${t}_audit`)) problems.push(`Thiếu trigger: trg_${t}_audit`);
  }

  const views = (
    (await db.query(`SELECT viewname AS name FROM pg_views WHERE schemaname = 'public'`)).rows as {
      name: string;
    }[]
  ).map((r) => r.name);
  if (!views.includes('v_invoice_balance')) problems.push('Thiếu view: v_invoice_balance');

  if (problems.length > 0) {
    throw new Error(`Schema không đạt chuẩn:\n- ${problems.join('\n- ')}`);
  }
}
