/* =====================================================================================
 * EduCenterPro — CANONICAL DATABASE SCHEMA (PostgreSQL, single source of truth)
 * =====================================================================================
 *
 * schema.ts + schema.{docs,tables,triggers,validate}.ts là định nghĩa DUY NHẤT của cấu trúc database.
 * Mọi thay đổi cấu trúc đều bắt đầu từ đây, sau đó mới viết migration trong migrations.ts.
 *
 * QUY ƯỚC (bắt buộc tuân thủ khi thêm bảng/cột mới):
 *
 * 1. Đặt tên: snake_case. Khóa chính `id INTEGER GENERATED BY DEFAULT AS IDENTITY
 *    PRIMARY KEY` (cho phép chèn id tường minh khi cần, vd: seed/test),
 *    trừ bảng nối nhiều-nhiều dùng khóa chính composite.
 *    Cột khóa ngoại đặt tên `<bang>_id` (vd: student_id -> students.id).
 *
 * 2. Thời gian: TEXT theo ISO-8601 'YYYY-MM-DD HH24:MI:SS' (giờ Việt Nam Asia/Ho_Chi_Minh),
 *    DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')) với PG session timezone=Asia/Ho_Chi_Minh.
 *    Cố tình dùng TEXT thay vì TIMESTAMPTZ để giữ nguyên semantics so sánh chuỗi
 *    và kiểu dữ liệu JS (string) như trước — tránh ripple đổi toàn bộ app.
 *    Mọi bảng nghiệp vụ chính có `created_at`; bảng mutable có thêm
 *    `updated_at` và trigger tự động chạm (BEFORE UPDATE, sửa trực tiếp NEW).
 *
 * 3. Tiền tệ: DOUBLE PRECISION, đơn vị VND, luôn có CHECK (amount >= 0).
 *    (Không dùng NUMERIC vì driver pg trả về string, gây vỡ logic JS.)
 *    Boolean: INTEGER với CHECK IN (0, 1).
 *
 * 4. Enum: TEXT + CHECK IN (...) TẠI DATABASE — không chỉ validate ở service.
 *    Giá trị enum phải đồng bộ với const trong service tương ứng.
 *
 * 5. CHÍNH SÁCH KHÓA NGOẠI (áp dụng đồng nhất):
 *    - Dữ liệu "sở hữu" (owned children)      -> ON DELETE CASCADE
 *    - Tham chiếu "tùy chọn" (optional refs)   -> ON DELETE SET NULL
 *    - Phạm vi tenant (center_id)             -> ON DELETE RESTRICT
 *    - audit_logs / *_history: CỐ TÌNH không đặt FK — append-only, bất tử.
 *
 * 6. Mọi ràng buộc đều ĐẶT TÊN (CONSTRAINT fk_... / chk_...) để lỗi DB trả về
 *    có thể truy vết, và để validateSchema() kiểm tra được.
 *
 * 7. Trigger viết bằng PL/pgSQL, dạng BEFORE UPDATE sửa trực tiếp NEW —
 *    sạch hơn SQLite (không cần inner UPDATE, không lo trigger kích chéo).
 *    Mỗi bảng CHỈ CÓ ĐÚNG 1 trigger maintain (bài học từ bản SQLite).
 *
 * 8. TABLE_DOCS (schema.docs.ts) là DATA DICTIONARY sống: tài liệu cho từng bảng/cột,
 *    được kiểm tra bởi schema.test.ts (mọi bảng trong DB đều phải có mặt).
 * =================================================================================== */

/**
 * Phiên bản schema PostgreSQL — đánh số lại từ 1 (baseline PG).
 * Không liên quan đến dãy version của SQLite cũ.
 */
export const SCHEMA_VERSION = 1;

/* B3-3: nội dung chia theo file (pure move) — importer chỉ cần './schema'. */
export * from './schema.docs';
export { createSchema } from './schema.tables';
export { createTriggers, createHistoryTables, createViews } from './schema.triggers';
export { validateSchema } from './schema.validate';
