/* createSchema — CREATE TABLE/INDEX toàn bộ bảng (quy ước: xem đầu schema.ts). B3-3: tách khỏi schema.ts. */
import type { Db } from './pg-compat';

/* -------------------------------------------------------------------------------------
 * createSchema — tạo toàn bộ bảng (idempotent — IF NOT EXISTS).
 * PostgreSQL baseline: DB mới nhận đầy đủ FK + CHECK + trigger + view.
 * Không còn khái niệm 'DB cũ SQLite' — migration SQLite->PG là script riêng
 * (xem scripts/migrate-sqlite-to-pg.ts).
 * ----------------------------------------------------------------------------------- */
/**
 * QUY TẮC NÂNG CẤP: createSchema chạy TRƯỚC runMigrations (initDatabase). Trên DB cũ, CREATE TABLE IF NOT
 * EXISTS là no-op nên cột mới trong CREATE TABLE chưa tồn tại -> mọi INDEX/ALTER trên cột do migration
 * thêm (vd v22 reset_requests.center_id, v23 credits.source_invoice_id/payments.credit_id) chỉ được tạo
 * trong migration (DB mới cũng chạy migration). Bảng MỚI hoàn toàn thì index ngay sau CREATE TABLE được.
 */
export async function createSchema(db: Db): Promise<void> {
  await db.exec(`

-- ================= BẢNG NỀN TẢNG =================
CREATE TABLE IF NOT EXISTS centers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subdomain TEXT UNIQUE,
  phone TEXT,
  address TEXT,
  plan TEXT NOT NULL DEFAULT 'standard'
    CONSTRAINT chk_centers_plan CHECK (plan IN ('basic', 'standard', 'premium')),
  plan_expires_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= NHÂN SỰ & ĐÀO TẠO =================
-- teachers tạo TRƯỚC users vì users.teacher_id REFERENCES teachers(id)
CREATE TABLE IF NOT EXISTS teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_teachers_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  subject TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'staff'
    CONSTRAINT chk_users_role CHECK (role IN ('superadmin', 'admin', 'staff', 'teacher')),
  name TEXT NOT NULL,
  center_id INTEGER
    CONSTRAINT fk_users_center REFERENCES centers(id) ON DELETE RESTRICT,
  teacher_id INTEGER
    CONSTRAINT fk_users_teacher REFERENCES teachers(id) ON DELETE SET NULL,
  token_version INTEGER NOT NULL DEFAULT 1, -- D2: tăng khi đổi pass/khóa TK để thu hồi access token ngay
  is_active BOOLEAN NOT NULL DEFAULT true, -- D2: false = tài khoản bị khóa, từ chối login + mọi request
  must_change_password BOOLEAN NOT NULL DEFAULT false, -- v25 (N-5): mật khẩu tạm -> buộc đổi
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  -- v22: chỉ superadmin được không thuộc trung tâm nào (NULL = phạm vi toàn hệ thống)
  CONSTRAINT chk_users_center CHECK (role = 'superadmin' OR center_id IS NOT NULL)
);

-- ================= PHÂN QUYỀN (RBAC) =================
-- Permission: quyền hạn nguyên tử, định danh dạng 'resource.action' (vd: 'students.delete').
-- Role: nhóm quyền, có thể là system role (cố định) hoặc custom role (admin tự tạo).
-- User có quyền = hợp của permissions từ role chính (users.role) + các custom roles (user_roles).

CREATE TABLE IF NOT EXISTS permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,           -- vd: 'students.delete'
  name TEXT NOT NULL,                  -- tên hiển thị tiếng Việt
  description TEXT,                    -- mô tả chi tiết
  module TEXT NOT NULL,                -- nhóm module: 'students', 'invoices', 'system', ...
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,                  -- vd: 'admin', 'receptionist' (custom); v22: duy nhất theo trung tâm
  name TEXT NOT NULL,
  description TEXT,
  center_id INTEGER                    -- NULL = system role dùng chung; có center_id = role riêng của trung tâm
    CONSTRAINT fk_roles_center REFERENCES centers(id) ON DELETE CASCADE,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,  -- system role không được xóa/sửa code
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);
-- v22: mã role duy nhất theo phạm vi (system role toàn cục, custom role theo trung tâm)
CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_system_code ON roles(code) WHERE center_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_center_code ON roles(center_id, code) WHERE center_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id INTEGER NOT NULL
    CONSTRAINT fk_rp_role REFERENCES roles(id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL
    CONSTRAINT fk_rp_perm REFERENCES permissions(id) ON DELETE CASCADE,
  -- scope: phạm vi áp dụng của quyền này trong role ('own' | 'center' | 'all')
  scope TEXT NOT NULL DEFAULT 'center'
    CONSTRAINT chk_rp_scope CHECK (scope IN ('own', 'center', 'all')),
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INTEGER NOT NULL
    CONSTRAINT fk_ur_user REFERENCES users(id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL
    CONSTRAINT fk_ur_role REFERENCES roles(id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS center_settings (
  center_id INTEGER NOT NULL
    CONSTRAINT fk_center_settings_center REFERENCES centers(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT,
  PRIMARY KEY (center_id, key)
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);


CREATE TABLE IF NOT EXISTS students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_students_center REFERENCES centers(id) ON DELETE RESTRICT,
  code TEXT NOT NULL, -- v22: duy nhất theo trung tâm (uq_students_center_code)
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  dob TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'studying'
    CONSTRAINT chk_students_status CHECK (status IN ('studying', 'paused', 'quit')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT uq_students_center_code UNIQUE (center_id, code)
);

CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_rooms_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 30
    CONSTRAINT chk_rooms_capacity CHECK (capacity > 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS classes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_classes_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  teacher_id INTEGER
    CONSTRAINT fk_classes_teacher REFERENCES teachers(id) ON DELETE SET NULL,
  room_id INTEGER
    CONSTRAINT fk_classes_room REFERENCES rooms(id) ON DELETE SET NULL,
  schedule TEXT NOT NULL DEFAULT '[]',
  start_date TEXT,
  end_date TEXT,
  tuition_fee DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_classes_fee CHECK (tuition_fee >= 0),
  max_students INTEGER NOT NULL DEFAULT 30
    CONSTRAINT chk_classes_max CHECK (max_students > 0),
  status TEXT NOT NULL DEFAULT 'active'
    CONSTRAINT chk_classes_status CHECK (status IN ('active', 'inactive')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_enrollments_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_enrollments_class REFERENCES classes(id) ON DELETE CASCADE,
  enrolled_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  status TEXT NOT NULL DEFAULT 'active'
    CONSTRAINT chk_enrollments_status CHECK (status IN ('active', 'inactive')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(student_id, class_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_sessions_class REFERENCES classes(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  topic TEXT,
  checkin_code TEXT,
  checkin_date TEXT,
  teacher_id INTEGER
    CONSTRAINT fk_sessions_teacher REFERENCES teachers(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'scheduled'
    CONSTRAINT chk_sessions_status CHECK (status IN ('scheduled', 'cancelled')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(class_id, date),
  -- Chống race trùng mã điểm danh (2 request đồng thời sinh cùng mã)
  UNIQUE(checkin_date, checkin_code)
);

CREATE TABLE IF NOT EXISTS attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL
    CONSTRAINT fk_attendance_session REFERENCES sessions(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_attendance_student REFERENCES students(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'present'
    CONSTRAINT chk_attendance_status CHECK (status IN ('present', 'absent', 'late')),
  note TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(session_id, student_id)
);

CREATE TABLE IF NOT EXISTS teacher_checkins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL
    CONSTRAINT fk_checkins_session REFERENCES sessions(id) ON DELETE CASCADE,
  teacher_id INTEGER NOT NULL
    CONSTRAINT fk_checkins_teacher REFERENCES teachers(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(session_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS salary_rules (
  teacher_id INTEGER PRIMARY KEY
    CONSTRAINT fk_salary_teacher REFERENCES teachers(id) ON DELETE CASCADE,
  per_session_amount DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_salary_amount CHECK (per_session_amount >= 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- v23: đơn giá theo ngày hiệu lực (đổi đơn giá không viết lại lương tháng cũ)
CREATE TABLE IF NOT EXISTS salary_rate_history (
  teacher_id INTEGER NOT NULL
    CONSTRAINT fk_srh_teacher REFERENCES teachers(id) ON DELETE CASCADE,
  effective_from TEXT NOT NULL,
  per_session_amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_srh_amount CHECK (per_session_amount >= 0),
  changed_by INTEGER
    CONSTRAINT fk_srh_user REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT pk_salary_rate_history PRIMARY KEY (teacher_id, effective_from)
);

-- v24: tháng lương đã chốt (J-A8)
CREATE TABLE IF NOT EXISTS payroll_closures (
  center_id INTEGER NOT NULL
    CONSTRAINT fk_payroll_closures_center REFERENCES centers(id) ON DELETE CASCADE,
  month TEXT NOT NULL CONSTRAINT chk_payroll_closures_month CHECK (month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  closed_by INTEGER
    CONSTRAINT fk_payroll_closures_user REFERENCES users(id) ON DELETE SET NULL,
  closed_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  snapshot JSONB, -- v25 (N-1): bảng lương chụp lúc chốt
  CONSTRAINT pk_payroll_closures PRIMARY KEY (center_id, month)
);

-- ================= TÀI CHÍNH =================
CREATE TABLE IF NOT EXISTS invoices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_invoices_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_invoices_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_invoices_class REFERENCES classes(id) ON DELETE SET NULL,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_invoices_amount CHECK (amount >= 0),
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'unpaid'
    CONSTRAINT chk_invoices_status CHECK (status IN ('unpaid', 'partial', 'paid')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id INTEGER NOT NULL
    CONSTRAINT fk_payments_invoice REFERENCES invoices(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_payments_amount CHECK (amount > 0 OR (amount < 0 AND method = 'refund')),
  paid_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  method TEXT,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'confirmed'
    CONSTRAINT chk_payments_status CHECK (status IN ('pending', 'confirmed', 'rejected')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payment_txns (
  ref TEXT PRIMARY KEY,
  invoice_id INTEGER NOT NULL
    CONSTRAINT fk_txns_invoice REFERENCES invoices(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_txns_amount CHECK (amount > 0),
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_txns_status CHECK (status IN ('pending', 'confirmed', 'failed', 'rejected', 'needs_review')),
  query_attempts INTEGER NOT NULL DEFAULT 0,
  vnp_create_date TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);
-- v23: đối soát VNPay quét pending theo created_at; FK invoice_id CASCADE cần index khi xóa hóa đơn
CREATE INDEX IF NOT EXISTS idx_txns_pending ON payment_txns(created_at) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_txns_invoice ON payment_txns(invoice_id);

CREATE TABLE IF NOT EXISTS parents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_parents_center REFERENCES centers(id) ON DELETE RESTRICT,
  phone TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  referral_code TEXT UNIQUE,
  token_version INTEGER NOT NULL DEFAULT 1, -- D2: tăng khi đổi pass/khóa TK để thu hồi access token ngay
  is_active BOOLEAN NOT NULL DEFAULT true, -- D2: false = tài khoản bị khóa, từ chối login + mọi request
  zalo_consent TEXT DEFAULT 'unknown'
    CONSTRAINT chk_parents_zalo_consent CHECK (zalo_consent IN ('granted','denied','unknown')),
  must_change_password BOOLEAN NOT NULL DEFAULT false, -- v25 (N-5): mật khẩu tạm -> buộc đổi
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(center_id, phone)
);

CREATE TABLE IF NOT EXISTS parent_students (
  parent_id INTEGER NOT NULL
    CONSTRAINT fk_ps_parent REFERENCES parents(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_ps_student REFERENCES students(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (parent_id, student_id)
);

CREATE TABLE IF NOT EXISTS credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id INTEGER NOT NULL
    CONSTRAINT fk_credits_parent REFERENCES parents(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_credits_amount CHECK (amount > 0),
  reason TEXT,
  used_amount DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_credits_used CHECK (used_amount >= 0),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  center_id INTEGER
    CONSTRAINT fk_credits_center REFERENCES centers(id) ON DELETE CASCADE,
  source_invoice_id INTEGER
    CONSTRAINT fk_credits_source_invoice REFERENCES invoices(id) ON DELETE SET NULL,
  voided_at TEXT,
  CONSTRAINT chk_credits_used_lte CHECK (used_amount <= amount)
);
-- v23 tạo (KHÔNG đặt ở đây — xem quy tắc đầu createSchema): idx_credits_source_invoice, và
-- payments.credit_id INTEGER REFERENCES credits(id) ON DELETE SET NULL + idx_payments_credit (FK tới bảng
-- tạo sau payments). Không CHECK method='credit' -> credit_id NOT NULL: SET NULL khi xóa credit sẽ vỡ check;
-- ràng buộc nằm ở code (nhân viên không ghi được method 'credit').

-- ================= CỔNG PHỤ HUYNH =================

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_leaves_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_leaves_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_leaves_class REFERENCES classes(id) ON DELETE SET NULL,
  from_date TEXT NOT NULL,
  to_date TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_leaves_status CHECK (status IN ('pending', 'approved', 'rejected')),
  decided_by INTEGER
    CONSTRAINT fk_leaves_decider REFERENCES users(id) ON DELETE SET NULL,
  decided_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT chk_leaves_dates CHECK (to_date >= from_date)
);

CREATE TABLE IF NOT EXISTS grades (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_grades_center REFERENCES centers(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_grades_student REFERENCES students(id) ON DELETE CASCADE,
  class_id INTEGER
    CONSTRAINT fk_grades_class REFERENCES classes(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  score DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_grades_score CHECK (score >= 0),
  max_score DOUBLE PRECISION NOT NULL DEFAULT 10
    CONSTRAINT chk_grades_max CHECK (max_score > 0),
  comment TEXT,
  created_by INTEGER
    CONSTRAINT fk_grades_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT chk_grades_score_lte CHECK (score <= max_score)
);

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_reviews_center REFERENCES centers(id) ON DELETE RESTRICT,
  parent_id INTEGER
    CONSTRAINT fk_reviews_parent REFERENCES parents(id) ON DELETE SET NULL,
  rating INTEGER NOT NULL
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_reviews_status CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT uq_reviews_parent_center UNIQUE (parent_id, center_id)
);

CREATE TABLE IF NOT EXISTS referrals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_parent_id INTEGER NOT NULL
    CONSTRAINT fk_referrals_referrer REFERENCES parents(id) ON DELETE CASCADE,
  referred_phone TEXT,
  referred_student_id INTEGER
    CONSTRAINT fk_referrals_student REFERENCES students(id) ON DELETE SET NULL,
  center_id INTEGER
    CONSTRAINT fk_referrals_center REFERENCES centers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_referrals_status CHECK (status IN ('pending', 'rewarded')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= BÀI TẬP / QUIZ =================
CREATE TABLE IF NOT EXISTS rubrics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_rubrics_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  created_by INTEGER
    CONSTRAINT fk_rubrics_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rubric_criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rubric_id INTEGER NOT NULL
    CONSTRAINT fk_criteria_rubric REFERENCES rubrics(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  max_score DOUBLE PRECISION NOT NULL DEFAULT 10
    CONSTRAINT chk_criteria_max CHECK (max_score > 0),
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_criteria_pos CHECK (position >= 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS homework (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_homework_center REFERENCES centers(id) ON DELETE RESTRICT,
  class_id INTEGER NOT NULL
    CONSTRAINT fk_homework_class REFERENCES classes(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'published'
    CONSTRAINT chk_homework_status CHECK (status IN ('draft', 'scheduled', 'published')),
  publish_at TEXT,
  max_score DOUBLE PRECISION
    CONSTRAINT chk_homework_max CHECK (max_score IS NULL OR max_score > 0),
  close_date TEXT,
  kind TEXT NOT NULL DEFAULT 'homework'
    CONSTRAINT chk_homework_kind CHECK (kind IN ('homework', 'quiz')),
  rubric_id INTEGER
    CONSTRAINT fk_homework_rubric REFERENCES rubrics(id) ON DELETE SET NULL,
  max_attempts INTEGER
    CONSTRAINT chk_homework_max_attempts CHECK (max_attempts IS NULL OR max_attempts BETWEEN 1 AND 100),
  created_by INTEGER
    CONSTRAINT fk_homework_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS homework_attachments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_attachments_hw REFERENCES homework(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'link'
    CONSTRAINT chk_attachments_kind CHECK (kind IN ('link', 'file', 'audio', 'video')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS homework_targets (
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_targets_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_targets_student REFERENCES students(id) ON DELETE CASCADE,
  due_date TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_completions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_completions_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_completions_student REFERENCES students(id) ON DELETE CASCADE,
  completed_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  completed_by TEXT NOT NULL DEFAULT 'parent'
    CONSTRAINT chk_completions_by CHECK (completed_by IN ('parent', 'teacher', 'student')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_scores (
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_scores_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_scores_student REFERENCES students(id) ON DELETE CASCADE,
  score DOUBLE PRECISION
    CONSTRAINT chk_scores_value CHECK (score IS NULL OR score >= 0),
  feedback TEXT,
  graded_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  graded_by INTEGER
    CONSTRAINT fk_scores_grader REFERENCES users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE(homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS homework_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_submissions_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_submissions_student REFERENCES students(id) ON DELETE CASCADE,
  file_url TEXT,
  file_name TEXT,
  note TEXT,
  submitted_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  -- P1-6: nộp bài idempotent — 1 học viên chỉ có 1 bản nộp / bài tập
  CONSTRAINT uq_submissions_hw_student UNIQUE (homework_id, student_id)
);

CREATE TABLE IF NOT EXISTS quiz_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_qq_hw REFERENCES homework(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qq_pos CHECK (position >= 0),
  qtype TEXT NOT NULL DEFAULT 'single'
    CONSTRAINT chk_qq_qtype CHECK (qtype IN ('single','multiple','truefalse','essay')),
  question TEXT NOT NULL,
  points DOUBLE PRECISION NOT NULL DEFAULT 1
    CONSTRAINT chk_qq_points CHECK (points > 0),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qo_question REFERENCES quiz_questions(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qo_pos CHECK (position >= 0),
  text TEXT NOT NULL,
  is_correct INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qo_correct CHECK (is_correct IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_qa_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_qa_student REFERENCES students(id) ON DELETE CASCADE,
  score DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_qa_score CHECK (score >= 0),
  max_score DOUBLE PRECISION NOT NULL DEFAULT 0
    CONSTRAINT chk_qa_max CHECK (max_score >= 0),
  submitted_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS quiz_answers (
  attempt_id INTEGER NOT NULL
    CONSTRAINT fk_qans_attempt REFERENCES quiz_attempts(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qans_question REFERENCES quiz_questions(id) ON DELETE CASCADE,
  option_id INTEGER
    CONSTRAINT fk_qans_option REFERENCES quiz_options(id) ON DELETE SET NULL,
  answer_text TEXT,
  CONSTRAINT uq_quiz_answers_choice UNIQUE (attempt_id, question_id, option_id)
);

-- YC2 (v21): điểm chấm tay từng câu tự luận theo tiêu chí rubric.
-- 1 câu essay được chấm theo toàn bộ tiêu chí của rubric gắn với quiz.
CREATE TABLE IF NOT EXISTS quiz_essay_scores (
  homework_id INTEGER NOT NULL
    CONSTRAINT fk_qes_hw REFERENCES homework(id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL
    CONSTRAINT fk_qes_student REFERENCES students(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qes_question REFERENCES quiz_questions(id) ON DELETE CASCADE,
  criterion_id INTEGER NOT NULL
    CONSTRAINT fk_qes_criterion REFERENCES rubric_criteria(id) ON DELETE CASCADE,
  score DOUBLE PRECISION NOT NULL
    CONSTRAINT chk_qes_score CHECK (score >= 0),
  graded_by INTEGER
    CONSTRAINT fk_qes_grader REFERENCES users(id) ON DELETE SET NULL,
  graded_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  CONSTRAINT pk_quiz_essay_scores PRIMARY KEY (homework_id, student_id, question_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS question_bank (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_qbank_center REFERENCES centers(id) ON DELETE RESTRICT,
  tag TEXT,
  subject TEXT,
  difficulty TEXT NOT NULL DEFAULT 'medium'
    CONSTRAINT chk_qbank_difficulty CHECK (difficulty IN ('easy','medium','hard')),
  qtype TEXT NOT NULL DEFAULT 'single'
    CONSTRAINT chk_qbank_qtype CHECK (qtype IN ('single','multiple','truefalse','essay')),
  question TEXT NOT NULL,
  points DOUBLE PRECISION NOT NULL DEFAULT 1
    CONSTRAINT chk_qbank_points CHECK (points > 0),
  created_by INTEGER
    CONSTRAINT fk_qbank_creator REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS question_bank_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL
    CONSTRAINT fk_qbo_question REFERENCES question_bank(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qbo_pos CHECK (position >= 0),
  text TEXT NOT NULL,
  is_correct INTEGER NOT NULL DEFAULT 0
    CONSTRAINT chk_qbo_correct CHECK (is_correct IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= TUYỂN SINH & TĂNG TRƯỞNG =================
CREATE TABLE IF NOT EXISTS trial_registrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_trials_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  class_id INTEGER
    CONSTRAINT fk_trials_class REFERENCES classes(id) ON DELETE SET NULL,
  desired_date TEXT,
  note TEXT,
  referral_code TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CONSTRAINT chk_trials_status CHECK (status IN ('new', 'contacted', 'converted')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_leads_center REFERENCES centers(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  source TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CONSTRAINT chk_leads_status CHECK (status IN ('new', 'contacted', 'trial', 'enrolled', 'lost')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- ================= VẬN HÀNH =================
CREATE TABLE IF NOT EXISTS reminders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_reminders_center REFERENCES centers(id) ON DELETE RESTRICT,
  invoice_id INTEGER
    CONSTRAINT fk_reminders_invoice REFERENCES invoices(id) ON DELETE SET NULL,
  student_id INTEGER
    CONSTRAINT fk_reminders_student REFERENCES students(id) ON DELETE SET NULL,
  phone TEXT,
  kind TEXT NOT NULL DEFAULT 'overdue'
    CONSTRAINT chk_reminders_kind CHECK (kind IN ('overdue','upcoming','receipt','test','absence','leave_result','payment_confirmed','grade','homework','general')),
  status TEXT NOT NULL DEFAULT 'sent'
    CONSTRAINT chk_reminders_status CHECK (status IN ('sending', 'sent', 'failed', 'demo')),
  message TEXT,
  response TEXT,
  -- Khóa chống gửi trùng ZNS: invoiceId:kind:ngày VN (migration v15 + unique index partial)
  dedup_key TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES parents(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CONSTRAINT chk_refresh_kind CHECK (kind IN ('staff', 'parent')),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ,
  replaced_by TEXT,
  ip TEXT,
  user_agent TEXT,
  CONSTRAINT chk_refresh_owner CHECK (
    (user_id IS NOT NULL AND parent_id IS NULL) OR
    (user_id IS NULL AND parent_id IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_owner ON refresh_tokens(user_id, parent_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER,
  actor_id INTEGER,
  actor_name TEXT,
  actor_role TEXT,
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id INTEGER,
  summary TEXT NOT NULL,
  meta TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- P0 red-team: yêu cầu đặt lại mật khẩu (quên mật khẩu) của staff/phụ huynh.
-- Luồng trung thực cho demo: user gửi yêu cầu -> admin xem danh sách và bấm
-- "Đặt lại mật khẩu" để sinh mật khẩu tạm (chưa có hạ tầng email/SMS).
CREATE TABLE IF NOT EXISTS reset_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifier TEXT NOT NULL, -- username (staff) hoặc số điện thoại (parent)
  kind TEXT NOT NULL CONSTRAINT chk_reset_requests_kind CHECK (kind IN ('staff', 'parent')),
  center_id INTEGER
    CONSTRAINT fk_reset_requests_center REFERENCES centers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CONSTRAINT chk_reset_requests_status CHECK (status IN ('pending', 'processed')),
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_reset_requests_status ON reset_requests(status, created_at DESC);
-- idx_reset_requests_center (center_id, status): do v22 tạo (cột center_id thêm ở v22).

-- v22: sổ file upload (ai tải, trung tâm nào) — DELETE kiểm quyền sở hữu + tham chiếu
CREATE TABLE IF NOT EXISTS uploads (
  filename TEXT PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_uploads_center REFERENCES centers(id) ON DELETE CASCADE,
  uploaded_by INTEGER
    CONSTRAINT fk_uploads_user REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- v22: chống brute-force liên kết con (mã HV + ngày sinh)
CREATE TABLE IF NOT EXISTS parent_link_failures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  center_id INTEGER
    CONSTRAINT fk_plf_center REFERENCES centers(id) ON DELETE CASCADE,
  parent_id INTEGER
    CONSTRAINT fk_plf_parent REFERENCES parents(id) ON DELETE CASCADE,
  student_code TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_plf_parent ON parent_link_failures(parent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_plf_code ON parent_link_failures(center_id, student_code, created_at);
CREATE INDEX IF NOT EXISTS idx_submissions_file_url ON homework_submissions(file_url) WHERE file_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attachments_url ON homework_attachments(url);

`);
}
